const nodeList = [
    { name: "Luciano Henrique Trindade", options: {size: 8.0, label: "Luciano Henrique Trindade", type: "image", image: "public/Luciano Henrique Trindade.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Rogerio Deitali Bruno", options: {size: 8.0, label: "Rogerio Deitali Bruno", type: "image", image: "public/Rogerio Deitali Bruno.jpg", color: '#330000', labelColor:  '#330000'} },
    { name: "Emanoel Fabiano Menezes Pereira", options: {size: 8.0, label: "Emanoel Fabiano Menezes Pereira", type: "image", image: "public/Emanoel Fabiano Menezes Pereira.jpg", color: '#339966', labelColor:  '#339966'} },
    { name: "Wilian Ramalho Feitosa", options: {size: 8.0, label: "Wilian Ramalho Feitosa", type: "image", image: "public/Wilian Ramalho Feitosa.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Julio Samuel Savio Bernardo", options: {size: 16.0, label: "Julio Samuel Savio Bernardo", type: "image", image: "public/Julio Samuel Savio Bernardo.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Jeferson Antunes", options: {size: 8.0, label: "Jeferson Antunes", type: "image", image: "public/Jeferson Antunes.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Irando Alves Martins Neto", options: {size: 8.0, label: "Irando Alves Martins Neto", type: "image", image: "public/Irando Alves Martins Neto.jpg", color: '#999933', labelColor:  '#999933'} },
    { name: "Renato Cristiano Montanher", options: {size: 11.313708498984761, label: "Renato Cristiano Montanher", type: "image", image: "public/Renato Cristiano Montanher.jpg", color: '#ffccff', labelColor:  '#ffccff'} },
    { name: "Jair Garcia dos Santos", options: {size: 8.0, label: "Jair Garcia dos Santos", type: "image", image: "public/Jair Garcia dos Santos.jpg", color: '#00cc99', labelColor:  '#00cc99'} },
    { name: "William Rosseti", options: {size: 13.856406460551018, label: "William Rosseti", type: "image", image: "public/William Rosseti.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Ana Paula Rodrigues Magalhaes de Barros", options: {size: 8.0, label: "Ana Paula Rodrigues Magalhaes de Barros", type: "image", image: "public/Ana Paula Rodrigues Magalhaes de Barros.jpg", color: '#339966', labelColor:  '#339966'} },
    { name: "Ana Marcia Lima Costa", options: {size: 8.0, label: "Ana Marcia Lima Costa", type: "image", image: "public/Ana Marcia Lima Costa.jpg", color: '#00cc99', labelColor:  '#00cc99'} },
    { name: "Alessandro Emilio Teruzzi", options: {size: 11.313708498984761, label: "Alessandro Emilio Teruzzi", type: "image", image: "public/Alessandro Emilio Teruzzi.jpg", color: '#339966', labelColor:  '#339966'} },
    { name: "Idalise Bernardo Bage", options: {size: 16.0, label: "Idalise Bernardo Bage", type: "image", image: "public/Idalise Bernardo Bage.jpg", color: '#339966', labelColor:  '#339966'} },
    { name: "Teresa Helena Buscato Martins", options: {size: 11.313708498984761, label: "Teresa Helena Buscato Martins", type: "image", image: "public/Teresa Helena Buscato Martins.jpg", color: '#999933', labelColor:  '#999933'} },
    { name: "Maria Cristina Stello Leite", options: {size: 11.313708498984761, label: "Maria Cristina Stello Leite", type: "image", image: "public/Maria Cristina Stello Leite.jpg", color: '#00cc99', labelColor:  '#00cc99'} },
    { name: "Igor Polezi Munhoz", options: {size: 8.0, label: "Igor Polezi Munhoz", type: "image", image: "public/Igor Polezi Munhoz.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Fernando da Silva Pardo", options: {size: 16.0, label: "Fernando da Silva Pardo", type: "image", image: "public/Fernando da Silva Pardo.jpg", color: '#999933', labelColor:  '#999933'} },
    { name: "Renato Marcon Pugliese", options: {size: 19.595917942265423, label: "Renato Marcon Pugliese", type: "image", image: "public/Renato Marcon Pugliese.jpg", color: '#330000', labelColor:  '#330000'} },
    { name: "Ricardo Normanha Ribeiro de Almeida", options: {size: 8.0, label: "Ricardo Normanha Ribeiro de Almeida", type: "image", image: "public/Ricardo Normanha Ribeiro de Almeida.jpg", color: '#0033ff', labelColor:  '#0033ff'} },
    { name: "Moacir Silva de Castro", options: {size: 13.856406460551018, label: "Moacir Silva de Castro", type: "image", image: "public/Moacir Silva de Castro.jpg", color: '#00cc99', labelColor:  '#00cc99'} },
    { name: "Flavia Roberta Torezin", options: {size: 8.0, label: "Flavia Roberta Torezin", type: "image", image: "public/Flavia Roberta Torezin.jpg", color: '#00cc99', labelColor:  '#00cc99'} },
    { name: "Claudia Almerinda de Souza Oliveira", options: {size: 11.313708498984761, label: "Claudia Almerinda de Souza Oliveira", type: "image", image: "public/Claudia Almerinda de Souza Oliveira.jpg", color: '#cc9999', labelColor:  '#cc9999'} },
    { name: "Luciana Cavalcanti Maia Santos", options: {size: 11.313708498984761, label: "Luciana Cavalcanti Maia Santos", type: "image", image: "public/Luciana Cavalcanti Maia Santos.jpg", color: '#990000', labelColor:  '#990000'} },
    { name: "Everaldo Paulo da Silva", options: {size: 16.0, label: "Everaldo Paulo da Silva", type: "image", image: "public/Everaldo Paulo da Silva.jpg", color: '#339966', labelColor:  '#339966'} },
];

// Export the nodeList for use in other modules
export { nodeList };
