const edgeList = [
    { source: "Alessandro Emilio Teruzzi", target: "Everaldo Paulo da Silva", options: { type: "line", weight: 0.4, label: "matemática, ensino, cálculo", size: 2 } },
    { source: "Alessandro Emilio Teruzzi", target: "Renato Marcon Pugliese", options: { type: "line", weight: 0.2348880878058813, label: "médio, ensino, história", size: 2 } },
    { source: "Ana Marcia Lima Costa", target: "Renato Marcon Pugliese", options: { type: "line", weight: 0.239731650742692, label: "reflexões, educação, ensino, médio, públicas", size: 2 } },
    { source: "Ana Paula Rodrigues Magalhaes de Barros", target: "Idalise Bernardo Bage", options: { type: "line", weight: 0.2574338543181771, label: "experiência, formação, docentes, olhar, digitais, ensino, tecnologias, professores, programa, matemática, contexto, avaliação", size: 2 } },
    { source: "Claudia Almerinda de Souza Oliveira", target: "Julio Samuel Savio Bernardo", options: { type: "line", weight: 0.2321035412742638, label: "ifsp, paulo, câmpus, pirituba", size: 2 } },
    { source: "Emanoel Fabiano Menezes Pereira", target: "Idalise Bernardo Bage", options: { type: "line", weight: 0.2276080409785175, label: "formação, uso, função, ensino, área, funções, professores, estudo, matemática, ingressantes", size: 2 } },
    { source: "Everaldo Paulo da Silva", target: "Fernando da Silva Pardo", options: { type: "line", weight: 0.3244428422615251, label: "ensino", size: 2 } },
    { source: "Everaldo Paulo da Silva", target: "Moacir Silva de Castro", options: { type: "line", weight: 0.2300894966542111, label: "ensino", size: 2 } },
    { source: "Everaldo Paulo da Silva", target: "Renato Marcon Pugliese", options: { type: "line", weight: 0.2348880878058813, label: "ensino", size: 2 } },
    { source: "Fernando da Silva Pardo", target: "Irando Alves Martins Neto", options: { type: "line", weight: 0.2752988806446741, label: "inglês, professor, implicações, práticas, digitais, ensino, língua, literatura, perspectivas, construção, sociais", size: 2 } },
    { source: "Fernando da Silva Pardo", target: "Renato Cristiano Montanher", options: { type: "line", weight: 0.2694351152071961, label: "inglês, línguas, conhecimento, ensino, língua, construção, literatura", size: 2 } },
    { source: "Fernando da Silva Pardo", target: "Renato Marcon Pugliese", options: { type: "line", weight: 0.2286232764633445, label: "reflexões, ensino, professor, implicações", size: 2 } },
    { source: "Flavia Roberta Torezin", target: "Idalise Bernardo Bage", options: { type: "line", weight: 0.2991830368027063, label: "formação, ensino, professores", size: 2 } },
    { source: "Idalise Bernardo Bage", target: "Moacir Silva de Castro", options: { type: "line", weight: 0.2707455769182841, label: "formação, ensino, proposta, paulo", size: 2 } },
    { source: "Igor Polezi Munhoz", target: "Wilian Ramalho Feitosa", options: { type: "line", weight: 0.2713416780982529, label: "impactos, study, organizacional, caso, relação, uso, análise, influence, gestão, qualidade, networks, implantação, comercial, operacionalização, paulo, estudo, inovação, green, digital, case, assessing", size: 2 } },
    { source: "Jair Garcia dos Santos", target: "Jeferson Antunes", options: { type: "line", weight: 0.2870663768509254, label: "análise, pesquisa, educação, ensino, sustentável, superior, desenvolvimento, estudantes", size: 2 } },
    { source: "Julio Samuel Savio Bernardo", target: "Maria Cristina Stello Leite", options: { type: "line", weight: 0.2325061496276285, label: "cidade, paulo", size: 2 } },
    { source: "Julio Samuel Savio Bernardo", target: "William Rosseti", options: { type: "line", weight: 0.26233381679809, label: "pirituba, análise, cidades, ifsp, cidade, paulo, região", size: 2 } },
    { source: "Luciana Cavalcanti Maia Santos", target: "Maria Cristina Stello Leite", options: { type: "line", weight: 0.2783613410670248, label: "ensino, cidade, paulo, urbanização, imagens", size: 2 } },
    { source: "Luciana Cavalcanti Maia Santos", target: "William Rosseti", options: { type: "line", weight: 0.2568166555809655, label: "pirituba, análise, cidades, ifsp, cidade, paulo, estudo, região, brasil", size: 2 } },
    { source: "Luciano Henrique Trindade", target: "William Rosseti", options: { type: "line", weight: 0.2454238228928462, label: "operações, relação, formação, pirituba, conhecimento, urbana, análise, cidades, importância, inteligentes, gestão, cidade, resiliência, estudo, projetos, brasil, consumo", size: 2 } },
    { source: "Moacir Silva de Castro", target: "Renato Marcon Pugliese", options: { type: "line", weight: 0.3828207467443881, label: "docente, educação, ensino, física, básica, instituto, paulo, escolar, federal", size: 2 } },
    { source: "Renato Cristiano Montanher", target: "Teresa Helena Buscato Martins", options: { type: "line", weight: 0.2367160382369996, label: "inglês, experiência, conhecimento, uso, relato, ensino, língua, construção", size: 2 } },
    { source: "Renato Marcon Pugliese", target: "Ricardo Normanha Ribeiro de Almeida", options: { type: "line", weight: 0.2644542653481614, label: "políticas, ensino, trabalho, brasil", size: 2 } },
    { source: "Rogerio Deitali Bruno", target: "Teresa Helena Buscato Martins", options: { type: "line", weight: 0.2631174057921088, label: "campus, processo, ifsp, construção, curso", size: 2 } },
];

// Export the edgeList for use in other modules
export { edgeList };
